controller_list:
  - name: fake_left arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_right arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_left_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - l_gripper_l_finger_joint
  - name: fake_right_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - r_gripper_l_finger_joint
initial:  # Define initial robot poses per group
#  - group: left arm
#    pose: home

  []